// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnKEmOfvmRL2kVSYaxTSWih8B03o8pis8',
    appId: '1:381984877526:web:84538bb6c22d0f639c1277',
    messagingSenderId: '381984877526',
    projectId: 'rx-dart-example-11-firebase',
    authDomain: 'rx-dart-example-11-firebase.firebaseapp.com',
    storageBucket: 'rx-dart-example-11-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiRaoPXLrQpn8R1ZsplZcq-jUoGmtsfQ',
    appId: '1:381984877526:android:197190fc921241029c1277',
    messagingSenderId: '381984877526',
    projectId: 'rx-dart-example-11-firebase',
    storageBucket: 'rx-dart-example-11-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-aYp7hly_YOLVox-6oOZXf4og3Ii5Cw',
    appId: '1:381984877526:ios:76878b4af6e6abaa9c1277',
    messagingSenderId: '381984877526',
    projectId: 'rx-dart-example-11-firebase',
    storageBucket: 'rx-dart-example-11-firebase.appspot.com',
    iosClientId: '381984877526-pn3ut54uip1aa95uee5s1q0raeqrhi9b.apps.googleusercontent.com',
    iosBundleId: 'com.niloy.rxDartExample11Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz-aYp7hly_YOLVox-6oOZXf4og3Ii5Cw',
    appId: '1:381984877526:ios:76878b4af6e6abaa9c1277',
    messagingSenderId: '381984877526',
    projectId: 'rx-dart-example-11-firebase',
    storageBucket: 'rx-dart-example-11-firebase.appspot.com',
    iosClientId: '381984877526-pn3ut54uip1aa95uee5s1q0raeqrhi9b.apps.googleusercontent.com',
    iosBundleId: 'com.niloy.rxDartExample11Firebase',
  );
}
